### PR TITLE
Cleaned up code

### PR DESCRIPTION
**Pull request by RJDiCosmo**
Refactored BucketServiceImpl Autowiring from field injection to constructor injection.
Refactored QuestionServiceImpl Autowiring from field injection to constructor injection.
Refactored QuestionServiceImpl deleteByBucketId method to reflect changes in autowiring.
Refactored SkillTypeServiceImpl Autowiring from field injection to constructor injection.
Refactored WeightServiceImpl Autowiring from field injection to constructor injection.
Refactored BucketController Autowiring from field injection to constructor injection.
Refactored QuestionController Autowiring from field injection to constructor injection.
Refactored SkillTypeController Autowiring from field injection to constructor injection.
Refactored WeightController Autowiring from field injection to constructor injection.

### CODE REVIEW

**Review by erchiggins — CHANGES_REQUESTED** [review]
Remove comments that were added, and since we're renaming/restructuring can you change skillService to skillTypeService in SkillTypeController?

**Comment by RJDiCosmo** [comment]
Requested changes have now been pushed.

**Review by erchiggins — CHANGES_REQUESTED** [review]
Still a comment in QuestionController. 
Fields and arguments which are services: questionService, etc. 
Fields and arguments which are repositories: questionRepository, etc
Rename DAOs to BucketRepository, etc. and package com.revature.screenforce.daos to com.revature.screenforce.repositories

**Comment by RJDiCosmo** [comment]
Names in DAO classes and package have now been refactored to Repository. References to services and repositories now have full names instead of abbreviations. Poor comments have been removed.

**Review by erchiggins — APPROVED** [review]

**Pull request merged**
